controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    # gps_sensor_broadcaster:
    #   type: gps_sensor_broadcaster/GPSSensorBroadcaster

    # imu_sensor_broadcaster:
    #   type: imu_sensor_broadcaster/IMUSensorBroadcaster




diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_back_wheel_joint"]
    right_wheel_names: ["right_back_wheel_joint"]

    wheel_separation: 0.53
    wheel_radius: 0.14

    odom_frame_id: "odom"
    # base_frame_id: "base_link"
    base_frame_id: "base_footprint"

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    enable_odom_tf: true

    publish_rate: 100.0
 
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0



# gps_sensor_broadcaster:
#    ros__parameters:
#      sensor_name: "gps_sensor"
#      frame_id: "gps_link"


# imu_sensor_broadcaster:
#   ros__parameters:
#     sensor_name: "imu_sensor"
#     frame_id: "imu_link"
